# Generated by Django 3.1.3 on 2021-01-19 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookstore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookstore',
            options={'verbose_name': 'Книжный магазин', 'verbose_name_plural': 'Книжные магазины'},
        ),
    ]
